# Query to get the list of observatories
# col names: uri, name, obs-id, type, country , location , habitat info 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
SELECT DISTINCT ?observatory
(GROUP_CONCAT(DISTINCT ?obs_id; SEPARATOR="|") AS ?obs_ids)
(GROUP_CONCAT(DISTINCT ?sampletypeuri; SEPARATOR="|") AS ?sampletypeuris)
(GROUP_CONCAT(DISTINCT ?marine_region; SEPARATOR="|") AS ?marine_regions)
(GROUP_CONCAT(DISTINCT ?marine_region_id; SEPARATOR="|") AS ?marine_region_ids)
(GROUP_CONCAT(DISTINCT ?country; SEPARATOR="|") AS ?countries)
(GROUP_CONCAT(DISTINCT ?biome; SEPARATOR="|") AS ?biomes)
WHERE  {
    ?observatory a emobon:Observatory .
    ?observatory emobon:sampleType ?sampletypeuri .
    ?observatory emobon:observatoryId ?obs_id .
    OPTIONAL { ?observatory emobon:originCountry ?country . }
    OPTIONAL { ?observatory emobon:marineRegionName ?marine_region . }
    OPTIONAL { ?observatory emobon:marineRegion ?marine_region_id . }
    OPTIONAL { ?observatory emobon:broadBiome ?biome . }
}
GROUP BY ?observatory