
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
  ?sample
  ?observatory
  ?event
  
  ?observations
  
  ?label_ammonium
  ?result_ammonium
  ?value_ammonium
  ?label_pressure
  ?result_pressure
  ?value_pressure
  ?label_sea_subsurf_temp
  ?result_sea_subsurf_temp
  ?value_sea_subsurf_temp
  ?taxonannotation
  ?taxonid
    ?sname
  ?lsuval
  ?ssuval
WHERE {
  ?sample a sosa:Sample .
  # link event
  ?sample sosa:isResultOf ?event .
  # link observatory
  ?event sampl:linkedToObservatory ?observatory .
  # Optional filters
  # name of observatory
  # depth filter
  
  ?observatory emobon:waterColumnDepth/qudt:numericValue ?depth_value .
  FILTER(?depth_value < 90) .
  # Marine Region (ID)
  ?observatory emobon:marineRegion ?mrgid . 
  FILTER regex(str(?mrgid), "http://marineregions.org/mrgid/1902") .
  ?event prov:startedAtTime ?datetime_begin . 
  
  # dateTime event
  FILTER(?datetime_begin >= "2023-09-04T14:30:09Z"^^xsd:date) .
  FILTER(?datetime_begin <= "2025-04-28T19:37:30Z"^^xsd:date) .
  # linking between taxon annotations and sample
  ?taxonannotation a prod:TaxonomicAnnotation .
  ?taxonannotation prod:ofSample ?sample .
  ?taxonannotation dct:identifier ?taxonid .
      
  ?taxonid dct:scientificName ?sname .
  ?sname onto:fts ("Gambierdiscus_australes~5") .
  OPTIONAL {
    ?taxonannotation prod:lsuRNA ?lsuval .
    FILTER(?lsuval >= 73) . 
  }
  OPTIONAL {
    ?taxonannotation prod:ssuRNA ?ssuval .
    FILTER(?ssuval >= 73) .  
  }
  FILTER(BOUND(?lsuval) || BOUND(?ssuval))
  ?observations a sosa:Observation .
  ?observations sosa:hasFeatureOfInterest ?sample .
    
  ?observations sosa:observedProperty ?ammonium .
  ?ammonium rdfs:label ?label_ammonium .
  ?label_ammonium onto:fts "ammonium~5" .
  ?observations sosa:hasResult ?result_ammonium .
  ?result_ammonium qudt:numericValue ?value_ammonium .
  FILTER(?value_ammonium <= 60)
  ?observations sosa:observedProperty ?pressure .
  ?pressure rdfs:label ?label_pressure .
  ?label_pressure onto:fts "pressure~5" .
  ?observations sosa:hasResult ?result_pressure .
  ?result_pressure qudt:numericValue ?value_pressure .
  FILTER(?value_pressure <= 49)
  ?observations sosa:observedProperty ?sea_subsurf_temp .
  ?sea_subsurf_temp rdfs:label ?label_sea_subsurf_temp .
  ?label_sea_subsurf_temp onto:fts "sea_subsurf_temp~5" .
  ?observations sosa:hasResult ?result_sea_subsurf_temp .
  ?result_sea_subsurf_temp qudt:numericValue ?value_sea_subsurf_temp .
  FILTER(?value_sea_subsurf_temp >= 5)
}