
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
  ?sample
  ?observatory
  ?event
  
  ?observations
  
  ?label_silicate
  ?result_silicate
  ?value_silicate
  ?label_sea_subsurf_salinity
  ?result_sea_subsurf_salinity
  ?value_sea_subsurf_salinity
  ?label_sea_subsurf_temp
  ?result_sea_subsurf_temp
  ?value_sea_subsurf_temp
  ?taxonannotation
  ?taxonid
    
  ?lsuval
  ?ssuval
WHERE {
  ?sample a sosa:Sample .
  # link event
  ?sample sosa:isResultOf ?event .
  # link observatory
  ?event sampl:linkedToObservatory ?observatory .
  # Optional filters
  # name of observatory
  
  ?observatory emobon:observatoryId ?observatory_id .
  ?observatory_id onto:fts ("OOB~5 HCMR-1~5 OSD74~5") .# depth filter
  
  ?observatory emobon:waterColumnDepth/qudt:numericValue ?depth_value .
  FILTER(?depth_value < 876.1978307119897) .
  # marineregion name
  ?observatory emobon:marineRegionName ?mrgn . 
  ?mrgn onto:fts ("Norwegian Sea~5") .
  ?event prov:startedAtTime ?datetime_begin . 
  
  # dateTime event
  FILTER(?datetime_begin >= "2024-08-19T17:24:43Z"^^xsd:date) .
  FILTER(?datetime_begin <= "2024-08-30T13:30:02Z"^^xsd:date) .
  # linking between taxon annotations and sample
  ?taxonannotation a prod:TaxonomicAnnotation .
  ?taxonannotation prod:ofSample ?sample .
  ?taxonannotation dct:identifier ?taxonid .
      
  OPTIONAL {
    ?taxonannotation prod:lsuRNA ?lsuval .
    FILTER(?lsuval >= 59.827589349035705) . 
  }
  OPTIONAL {
    ?taxonannotation prod:ssuRNA ?ssuval .
    FILTER(?ssuval >= 59.827589349035705) .  
  }
  FILTER(BOUND(?lsuval) || BOUND(?ssuval))
  ?observations a sosa:Observation .
  ?observations sosa:hasFeatureOfInterest ?sample .
    
  ?observations sosa:observedProperty ?silicate .
  ?silicate rdfs:label ?label_silicate .
  ?label_silicate onto:fts "silicate~5" .
  ?observations sosa:hasResult ?result_silicate .
  ?result_silicate qudt:numericValue ?value_silicate .
  FILTER(?value_silicate < 3.3548077179406555)
  ?observations sosa:observedProperty ?sea_subsurf_salinity .
  ?sea_subsurf_salinity rdfs:label ?label_sea_subsurf_salinity .
  ?label_sea_subsurf_salinity onto:fts "sea_subsurf_salinity~5" .
  ?observations sosa:hasResult ?result_sea_subsurf_salinity .
  ?result_sea_subsurf_salinity qudt:numericValue ?value_sea_subsurf_salinity .
  FILTER(?value_sea_subsurf_salinity <= 31.899187726012666)
  ?observations sosa:observedProperty ?sea_subsurf_temp .
  ?sea_subsurf_temp rdfs:label ?label_sea_subsurf_temp .
  ?label_sea_subsurf_temp onto:fts "sea_subsurf_temp~5" .
  ?observations sosa:hasResult ?result_sea_subsurf_temp .
  ?result_sea_subsurf_temp qudt:numericValue ?value_sea_subsurf_temp .
  FILTER(?value_sea_subsurf_temp >= 80.91602779515608)
}