
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
  ?sample
  ?observatory
  ?event
  
  ?observations
  
  ?label_redox_potential
  ?result_redox_potential
  ?value_redox_potential
  ?label_nitrate
  ?result_nitrate
  ?value_nitrate
  ?taxonannotation
  ?taxonid
    ?sname
  ?lsuval
  ?ssuval
WHERE {
  ?sample a sosa:Sample .
  # link event
  ?sample sosa:isResultOf ?event .
  # link observatory
  ?event sampl:linkedToObservatory ?observatory .
  # Optional filters
  # name of observatory
  # depth filter
  
  ?event prov:startedAtTime ?datetime_begin . 
  
  # dateTime event
  FILTER(?datetime_begin >= "2024-04-13T09:04:48Z"^^xsd:date) .
  FILTER(?datetime_begin <= "2024-09-24T18:28:53Z"^^xsd:date) .
  # linking between taxon annotations and sample
  ?taxonannotation a prod:TaxonomicAnnotation .
  ?taxonannotation prod:ofSample ?sample .
  ?taxonannotation dct:identifier ?taxonid .
      
  ?taxonid dct:scientificName ?sname .
  ?sname onto:fts ("actinobacterium_SCGC_AAA041-L13~5") .
  OPTIONAL {
    ?taxonannotation prod:lsuRNA ?lsuval .
    FILTER(?lsuval >= 1) . 
  }
  OPTIONAL {
    ?taxonannotation prod:ssuRNA ?ssuval .
    FILTER(?ssuval >= 1) .  
  }
  FILTER(BOUND(?lsuval) || BOUND(?ssuval))
  ?observations a sosa:Observation .
  ?observations sosa:hasFeatureOfInterest ?sample .
    
  ?observations sosa:observedProperty ?redox_potential .
  ?redox_potential rdfs:label ?label_redox_potential .
  ?label_redox_potential onto:fts "redox_potential~5" .
  ?observations sosa:hasResult ?result_redox_potential .
  ?result_redox_potential qudt:numericValue ?value_redox_potential .
  FILTER(?value_redox_potential < 17)
  ?observations sosa:observedProperty ?nitrate .
  ?nitrate rdfs:label ?label_nitrate .
  ?label_nitrate onto:fts "nitrate~5" .
  ?observations sosa:hasResult ?result_nitrate .
  ?result_nitrate qudt:numericValue ?value_nitrate .
  FILTER(?value_nitrate <= 67)
}