
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
  ?sample
  ?observatory
  ?event
  
  ?observations
  
  ?label_pressure
  ?result_pressure
  ?value_pressure
  ?label_nitrate
  ?result_nitrate
  ?value_nitrate
  ?taxonannotation
  ?taxonid
    ?sname
  ?rank
WHERE {
  ?sample a sosa:Sample .
  # link event
  ?sample sosa:isResultOf ?event .
  # link observatory
  ?event sampl:linkedToObservatory ?observatory .
  # Optional filters
  # name of observatory
  
  ?observatory emobon:observatoryId ?observatory_id .
  ?observatory_id onto:fts ("IUIEilat~5 MBAL4~5") .# depth filter
  
  ?event prov:startedAtTime ?datetime_begin . 
  
  # dateTime event
  FILTER(?datetime_begin >= "2025-09-25T13:40:08Z"^^xsd:date) .
  FILTER(?datetime_begin <= "2025-12-30T23:44:45Z"^^xsd:date) .
  # linking between taxon annotations and sample
  ?taxonannotation a prod:TaxonomicAnnotation .
  ?taxonannotation prod:ofSample ?sample .
  ?taxonannotation dct:identifier ?taxonid .
      
  ?taxonid dct:scientificName ?sname .
  ?sname onto:fts ("Dietzia~5") .
  ?taxonid dct:taxonRank ?rank .
  ?rank onto:fts ("family~5") .
  ?observations a sosa:Observation .
  ?observations sosa:hasFeatureOfInterest ?sample .
    
  ?observations sosa:observedProperty ?pressure .
  ?pressure rdfs:label ?label_pressure .
  ?label_pressure onto:fts "pressure~5" .
  ?observations sosa:hasResult ?result_pressure .
  ?result_pressure qudt:numericValue ?value_pressure .
  FILTER(?value_pressure < 81)
  ?observations sosa:observedProperty ?nitrate .
  ?nitrate rdfs:label ?label_nitrate .
  ?label_nitrate onto:fts "nitrate~5" .
  ?observations sosa:hasResult ?result_nitrate .
  ?result_nitrate qudt:numericValue ?value_nitrate .
  FILTER(?value_nitrate <= 60)
}