
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
  ?sample
  ?observatory
  ?event
  
  ?observations
  
  ?label_sea_subsurf_salinity
  ?result_sea_subsurf_salinity
  ?value_sea_subsurf_salinity
  ?label_chlorophyll
  ?result_chlorophyll
  ?value_chlorophyll
  ?taxonannotation
  ?taxonid
    ?sname
WHERE {
  ?sample a sosa:Sample .
  # link event
  ?sample sosa:isResultOf ?event .
  # link observatory
  ?event sampl:linkedToObservatory ?observatory .
  # Optional filters
  # name of observatory
  
  ?observatory emobon:observatoryId ?observatory_id .
  ?observatory_id onto:fts ("VB~5 LMO~5") .# depth filter
  
  ?observatory emobon:waterColumnDepth/qudt:numericValue ?depth_value .
  FILTER(?depth_value < 913.0344608070634) .
  ?event prov:startedAtTime ?datetime_begin . 
  
  # linking between taxon annotations and sample
  ?taxonannotation a prod:TaxonomicAnnotation .
  ?taxonannotation prod:ofSample ?sample .
  ?taxonannotation dct:identifier ?taxonid .
      
  ?taxonid dct:scientificName ?sname .
  ?sname onto:fts ("Phycicoccus~5") .
  ?observations a sosa:Observation .
  ?observations sosa:hasFeatureOfInterest ?sample .
    
  ?observations sosa:observedProperty ?sea_subsurf_salinity .
  ?sea_subsurf_salinity rdfs:label ?label_sea_subsurf_salinity .
  ?label_sea_subsurf_salinity onto:fts "sea_subsurf_salinity~5" .
  ?observations sosa:hasResult ?result_sea_subsurf_salinity .
  ?result_sea_subsurf_salinity qudt:numericValue ?value_sea_subsurf_salinity .
  FILTER(?value_sea_subsurf_salinity <= 31.13464110217894)
  ?observations sosa:observedProperty ?chlorophyll .
  ?chlorophyll rdfs:label ?label_chlorophyll .
  ?label_chlorophyll onto:fts "chlorophyll~5" .
  ?observations sosa:hasResult ?result_chlorophyll .
  ?result_chlorophyll qudt:numericValue ?value_chlorophyll .
  FILTER(?value_chlorophyll <= 48.48639476986207)
}