
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
  ?sample
  ?observatory
  ?event
  
  ?observations
  
  ?label_phosphate
  ?result_phosphate
  ?value_phosphate
  ?label_ammonium
  ?result_ammonium
  ?value_ammonium
  ?label_nitrate
  ?result_nitrate
  ?value_nitrate
  ?taxonannotation
  ?taxonid
    
  ?rank
  ?lsuval
  ?ssuval
WHERE {
  ?sample a sosa:Sample .
  # link event
  ?sample sosa:isResultOf ?event .
  # link observatory
  ?event sampl:linkedToObservatory ?observatory .
  # Optional filters
  # name of observatory
  # depth filter
  
  # Marine Region (ID)
  ?observatory emobon:marineRegion ?mrgid . 
  FILTER regex(str(?mrgid), "http://marineregions.org/mrgid/2353") .
  ?event prov:startedAtTime ?datetime_begin . 
  
  # dateTime event
  FILTER(?datetime_begin >= "2022-05-09T20:25:25Z"^^xsd:date) .
  FILTER(?datetime_begin <= "2025-04-28T19:51:33Z"^^xsd:date) .
  # linking between taxon annotations and sample
  ?taxonannotation a prod:TaxonomicAnnotation .
  ?taxonannotation prod:ofSample ?sample .
  ?taxonannotation dct:identifier ?taxonid .
      
  ?taxonid dct:taxonRank ?rank .
  ?rank onto:fts ("species~5") .
  OPTIONAL {
    ?taxonannotation prod:lsuRNA ?lsuval .
    FILTER(?lsuval >= 64.7596484294207) . 
  }
  OPTIONAL {
    ?taxonannotation prod:ssuRNA ?ssuval .
    FILTER(?ssuval >= 64.7596484294207) .  
  }
  FILTER(BOUND(?lsuval) || BOUND(?ssuval))
  ?observations a sosa:Observation .
  ?observations sosa:hasFeatureOfInterest ?sample .
    
  ?observations sosa:observedProperty ?phosphate .
  ?phosphate rdfs:label ?label_phosphate .
  ?label_phosphate onto:fts "phosphate~5" .
  ?observations sosa:hasResult ?result_phosphate .
  ?result_phosphate qudt:numericValue ?value_phosphate .
  FILTER(?value_phosphate < 80.77928898059558)
  ?observations sosa:observedProperty ?ammonium .
  ?ammonium rdfs:label ?label_ammonium .
  ?label_ammonium onto:fts "ammonium~5" .
  ?observations sosa:hasResult ?result_ammonium .
  ?result_ammonium qudt:numericValue ?value_ammonium .
  FILTER(?value_ammonium < 41.01638626880869)
  ?observations sosa:observedProperty ?nitrate .
  ?nitrate rdfs:label ?label_nitrate .
  ?label_nitrate onto:fts "nitrate~5" .
  ?observations sosa:hasResult ?result_nitrate .
  ?result_nitrate qudt:numericValue ?value_nitrate .
  FILTER(?value_nitrate >= 18.51126047252145)
}