
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
  ?sample
  ?observatory
  ?event
  
  ?observations
  
  ?label_sea_subsurf_salinity
  ?result_sea_subsurf_salinity
  ?value_sea_subsurf_salinity
  ?label_organism_count
  ?result_organism_count
  ?value_organism_count
  ?label_diss_oxygen
  ?result_diss_oxygen
  ?value_diss_oxygen
  ?taxonannotation
  ?taxonid
    
  ?rank
  ?lsuval
  ?ssuval
WHERE {
  ?sample a sosa:Sample .
  # link event
  ?sample sosa:isResultOf ?event .
  # link observatory
  ?event sampl:linkedToObservatory ?observatory .
  # Optional filters
  # name of observatory
  # depth filter
  
  # Marine Region (ID)
  ?observatory emobon:marineRegion ?mrgid . 
  FILTER regex(str(?mrgid), "http://marineregions.org/mrgid/4280") .
  # marineregion name
  ?observatory emobon:marineRegionName ?mrgn . 
  ?mrgn onto:fts ("Gulf of Eilat~5") .
  ?event prov:startedAtTime ?datetime_begin . 
  
  # dateTime event
  FILTER(?datetime_begin >= "2025-06-23T09:58:13Z"^^xsd:date) .
  FILTER(?datetime_begin <= "2025-07-27T06:56:25Z"^^xsd:date) .
  # linking between taxon annotations and sample
  ?taxonannotation a prod:TaxonomicAnnotation .
  ?taxonannotation prod:ofSample ?sample .
  ?taxonannotation dct:identifier ?taxonid .
      
  ?taxonid dct:taxonRank ?rank .
  ?rank onto:fts ("species~5") .
  OPTIONAL {
    ?taxonannotation prod:lsuRNA ?lsuval .
    FILTER(?lsuval >= 90) . 
  }
  OPTIONAL {
    ?taxonannotation prod:ssuRNA ?ssuval .
    FILTER(?ssuval >= 90) .  
  }
  FILTER(BOUND(?lsuval) || BOUND(?ssuval))
  ?observations a sosa:Observation .
  ?observations sosa:hasFeatureOfInterest ?sample .
    
  ?observations sosa:observedProperty ?sea_subsurf_salinity .
  ?sea_subsurf_salinity rdfs:label ?label_sea_subsurf_salinity .
  ?label_sea_subsurf_salinity onto:fts "sea_subsurf_salinity~5" .
  ?observations sosa:hasResult ?result_sea_subsurf_salinity .
  ?result_sea_subsurf_salinity qudt:numericValue ?value_sea_subsurf_salinity .
  FILTER(?value_sea_subsurf_salinity >= 29)
  ?observations sosa:observedProperty ?organism_count .
  ?organism_count rdfs:label ?label_organism_count .
  ?label_organism_count onto:fts "organism_count~5" .
  ?observations sosa:hasResult ?result_organism_count .
  ?result_organism_count qudt:numericValue ?value_organism_count .
  FILTER(?value_organism_count >= 98)
  ?observations sosa:observedProperty ?diss_oxygen .
  ?diss_oxygen rdfs:label ?label_diss_oxygen .
  ?label_diss_oxygen onto:fts "diss_oxygen~5" .
  ?observations sosa:hasResult ?result_diss_oxygen .
  ?result_diss_oxygen qudt:numericValue ?value_diss_oxygen .
  FILTER(?value_diss_oxygen >= 68)
}