
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
  ?sample
  ?observatory
  ?event
  
  ?observations
  
  ?label_pressure
  ?result_pressure
  ?value_pressure
  ?label_redox_potential
  ?result_redox_potential
  ?value_redox_potential
  ?taxonannotation
  ?taxonid
    
  ?lsuval
  ?ssuval
WHERE {
  ?sample a sosa:Sample .
  # link event
  ?sample sosa:isResultOf ?event .
  # link observatory
  ?event sampl:linkedToObservatory ?observatory .
  # Optional filters
  # name of observatory
  
  ?observatory emobon:observatoryId ?observatory_id .
  ?observatory_id onto:fts ("OSD74~5") .# depth filter
  
  # Marine Region (ID)
  ?observatory emobon:marineRegion ?mrgid . 
  FILTER regex(str(?mrgid), "http://marineregions.org/mrgid/4280") .
  # marineregion name
  ?observatory emobon:marineRegionName ?mrgn . 
  ?mrgn onto:fts ("Naples Gulf~5") .
  ?event prov:startedAtTime ?datetime_begin . 
  
  # dateTime event
  FILTER(?datetime_begin >= "2024-08-27T16:42:16Z"^^xsd:date) .
  FILTER(?datetime_begin <= "2025-11-27T05:48:23Z"^^xsd:date) .
  # linking between taxon annotations and sample
  ?taxonannotation a prod:TaxonomicAnnotation .
  ?taxonannotation prod:ofSample ?sample .
  ?taxonannotation dct:identifier ?taxonid .
      
  OPTIONAL {
    ?taxonannotation prod:lsuRNA ?lsuval .
    FILTER(?lsuval >= 32.95025217343617) . 
  }
  OPTIONAL {
    ?taxonannotation prod:ssuRNA ?ssuval .
    FILTER(?ssuval >= 32.95025217343617) .  
  }
  FILTER(BOUND(?lsuval) || BOUND(?ssuval))
  ?observations a sosa:Observation .
  ?observations sosa:hasFeatureOfInterest ?sample .
    
  ?observations sosa:observedProperty ?pressure .
  ?pressure rdfs:label ?label_pressure .
  ?label_pressure onto:fts "pressure~5" .
  ?observations sosa:hasResult ?result_pressure .
  ?result_pressure qudt:numericValue ?value_pressure .
  FILTER(?value_pressure < 22.395258953929087)
  ?observations sosa:observedProperty ?redox_potential .
  ?redox_potential rdfs:label ?label_redox_potential .
  ?label_redox_potential onto:fts "redox_potential~5" .
  ?observations sosa:hasResult ?result_redox_potential .
  ?result_redox_potential qudt:numericValue ?value_redox_potential .
  FILTER(?value_redox_potential <= 1.32408993039127)
}