
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
  ?sample
  ?observatory
  ?event
  
  ?observations
  
  ?label_ammonium
  ?result_ammonium
  ?value_ammonium
  ?taxonannotation
  ?taxonid
    
  ?lsuval
  ?ssuval
WHERE {
  ?sample a sosa:Sample .
  # link event
  ?sample sosa:isResultOf ?event .
  # link observatory
  ?event sampl:linkedToObservatory ?observatory .
  # Optional filters
  # name of observatory
  
  ?observatory emobon:observatoryId ?observatory_id .
  ?observatory_id onto:fts ("MBAL4~5 LMO~5") .# depth filter
  
  ?observatory emobon:waterColumnDepth/qudt:numericValue ?depth_value .
  FILTER(?depth_value > 158.27558706532585) .
  # Marine Region (ID)
  ?observatory emobon:marineRegion ?mrgid . 
  FILTER regex(str(?mrgid), "http://marineregions.org/mrgid/2359") .
  ?event prov:startedAtTime ?datetime_begin . 
  
  # dateTime event
  FILTER(?datetime_begin >= "2025-08-13T06:26:53Z"^^xsd:date) .
  FILTER(?datetime_begin <= "2025-12-13T11:21:06Z"^^xsd:date) .
  # linking between taxon annotations and sample
  ?taxonannotation a prod:TaxonomicAnnotation .
  ?taxonannotation prod:ofSample ?sample .
  ?taxonannotation dct:identifier ?taxonid .
      
  OPTIONAL {
    ?taxonannotation prod:lsuRNA ?lsuval .
    FILTER(?lsuval >= 39.75993179423598) . 
  }
  OPTIONAL {
    ?taxonannotation prod:ssuRNA ?ssuval .
    FILTER(?ssuval >= 39.75993179423598) .  
  }
  FILTER(BOUND(?lsuval) || BOUND(?ssuval))
  ?observations a sosa:Observation .
  ?observations sosa:hasFeatureOfInterest ?sample .
    
  ?observations sosa:observedProperty ?ammonium .
  ?ammonium rdfs:label ?label_ammonium .
  ?label_ammonium onto:fts "ammonium~5" .
  ?observations sosa:hasResult ?result_ammonium .
  ?result_ammonium qudt:numericValue ?value_ammonium .
  FILTER(?value_ammonium <= 47.04226973127372)
}