
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
  ?sample
  ?observatory
  ?event
  
  ?observations
  
  ?label_ammonium
  ?result_ammonium
  ?value_ammonium
  ?label_organism_count
  ?result_organism_count
  ?value_organism_count
  ?label_chlorophyll
  ?result_chlorophyll
  ?value_chlorophyll
  ?taxonannotation
  ?taxonid
    
  ?rank
WHERE {
  ?sample a sosa:Sample .
  # link event
  ?sample sosa:isResultOf ?event .
  # link observatory
  ?event sampl:linkedToObservatory ?observatory .
  # Optional filters
  # name of observatory
  # depth filter
  
  ?observatory emobon:waterColumnDepth/qudt:numericValue ?depth_value .
  FILTER(?depth_value < 574.5935314282602) .
  # Marine Region (ID)
  ?observatory emobon:marineRegion ?mrgid . 
  FILTER regex(str(?mrgid), "http://marineregions.org/mrgid/1906") .
  ?event prov:startedAtTime ?datetime_begin . 
  
  # dateTime event
  FILTER(?datetime_begin >= "2024-10-25T16:48:30Z"^^xsd:date) .
  FILTER(?datetime_begin <= "2025-02-06T00:19:57Z"^^xsd:date) .
  # linking between taxon annotations and sample
  ?taxonannotation a prod:TaxonomicAnnotation .
  ?taxonannotation prod:ofSample ?sample .
  ?taxonannotation dct:identifier ?taxonid .
      
  ?taxonid dct:taxonRank ?rank .
  ?rank onto:fts ("genus~5") .
  ?observations a sosa:Observation .
  ?observations sosa:hasFeatureOfInterest ?sample .
    
  ?observations sosa:observedProperty ?ammonium .
  ?ammonium rdfs:label ?label_ammonium .
  ?label_ammonium onto:fts "ammonium~5" .
  ?observations sosa:hasResult ?result_ammonium .
  ?result_ammonium qudt:numericValue ?value_ammonium .
  FILTER(?value_ammonium > 46.554709875235524)
  ?observations sosa:observedProperty ?organism_count .
  ?organism_count rdfs:label ?label_organism_count .
  ?label_organism_count onto:fts "organism_count~5" .
  ?observations sosa:hasResult ?result_organism_count .
  ?result_organism_count qudt:numericValue ?value_organism_count .
  FILTER(?value_organism_count < 19.275831164399293)
  ?observations sosa:observedProperty ?chlorophyll .
  ?chlorophyll rdfs:label ?label_chlorophyll .
  ?label_chlorophyll onto:fts "chlorophyll~5" .
  ?observations sosa:hasResult ?result_chlorophyll .
  ?result_chlorophyll qudt:numericValue ?value_chlorophyll .
  FILTER(?value_chlorophyll >= 66.45843808108354)
}