
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
  ?sample
  ?observatory
  ?event
  
  ?observations
  
  ?label_down_par
  ?result_down_par
  ?value_down_par
  ?label_phaeopigments
  ?result_phaeopigments
  ?value_phaeopigments
  ?label_pigments
  ?result_pigments
  ?value_pigments
  ?taxonannotation
  ?taxonid
    
  ?rank
WHERE {
  ?sample a sosa:Sample .
  # link event
  ?sample sosa:isResultOf ?event .
  # link observatory
  ?event sampl:linkedToObservatory ?observatory .
  # Optional filters
  # name of observatory
  
  ?observatory emobon:observatoryId ?observatory_id .
  ?observatory_id onto:fts ("IUIEilat~5") .# depth filter
  
  ?observatory emobon:waterColumnDepth/qudt:numericValue ?depth_value .
  FILTER(?depth_value <= 993) .
  # marineregion name
  ?observatory emobon:marineRegionName ?mrgn . 
  ?mrgn onto:fts ("Arctic Ocean~5") .
  ?event prov:startedAtTime ?datetime_begin . 
  
  # dateTime event
  FILTER(?datetime_begin >= "2023-09-28T00:21:39Z"^^xsd:date) .
  FILTER(?datetime_begin <= "2024-09-12T19:33:47Z"^^xsd:date) .
  # linking between taxon annotations and sample
  ?taxonannotation a prod:TaxonomicAnnotation .
  ?taxonannotation prod:ofSample ?sample .
  ?taxonannotation dct:identifier ?taxonid .
      
  ?taxonid dct:taxonRank ?rank .
  ?rank onto:fts ("species~5") .
  ?observations a sosa:Observation .
  ?observations sosa:hasFeatureOfInterest ?sample .
    
  ?observations sosa:observedProperty ?down_par .
  ?down_par rdfs:label ?label_down_par .
  ?label_down_par onto:fts "down_par~5" .
  ?observations sosa:hasResult ?result_down_par .
  ?result_down_par qudt:numericValue ?value_down_par .
  FILTER(?value_down_par < 18)
  ?observations sosa:observedProperty ?phaeopigments .
  ?phaeopigments rdfs:label ?label_phaeopigments .
  ?label_phaeopigments onto:fts "phaeopigments~5" .
  ?observations sosa:hasResult ?result_phaeopigments .
  ?result_phaeopigments qudt:numericValue ?value_phaeopigments .
  FILTER(?value_phaeopigments < 4)
  ?observations sosa:observedProperty ?pigments .
  ?pigments rdfs:label ?label_pigments .
  ?label_pigments onto:fts "pigments~5" .
  ?observations sosa:hasResult ?result_pigments .
  ?result_pigments qudt:numericValue ?value_pigments .
  FILTER(?value_pigments > 83)
}