
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
  ?sample
  ?observatory
  ?event
  
  ?observations
  
  ?label_phaeopigments
  ?result_phaeopigments
  ?value_phaeopigments
  ?label_pigments
  ?result_pigments
  ?value_pigments
  ?label_sea_surf_temp
  ?result_sea_surf_temp
  ?value_sea_surf_temp
  ?taxonannotation
  ?taxonid
    ?sname
WHERE {
  ?sample a sosa:Sample .
  # link event
  ?sample sosa:isResultOf ?event .
  # link observatory
  ?event sampl:linkedToObservatory ?observatory .
  # Optional filters
  # name of observatory
  
  ?observatory emobon:observatoryId ?observatory_id .
  ?observatory_id onto:fts ("ESC68N~5") .# depth filter
  
  ?observatory emobon:waterColumnDepth/qudt:numericValue ?depth_value .
  FILTER(?depth_value >= 653.9013207478612) .
  # Marine Region (ID)
  ?observatory emobon:marineRegion ?mrgid . 
  FILTER regex(str(?mrgid), "http://marineregions.org/mrgid/3558") .
  # marineregion name
  ?observatory emobon:marineRegionName ?mrgn . 
  ?mrgn onto:fts ("Atlantic Ocean~5") .
  ?event prov:startedAtTime ?datetime_begin . 
  
  # linking between taxon annotations and sample
  ?taxonannotation a prod:TaxonomicAnnotation .
  ?taxonannotation prod:ofSample ?sample .
  ?taxonannotation dct:identifier ?taxonid .
      
  ?taxonid dct:scientificName ?sname .
  ?sname onto:fts ("Fictibacillus~5") .
  ?observations a sosa:Observation .
  ?observations sosa:hasFeatureOfInterest ?sample .
    
  ?observations sosa:observedProperty ?phaeopigments .
  ?phaeopigments rdfs:label ?label_phaeopigments .
  ?label_phaeopigments onto:fts "phaeopigments~5" .
  ?observations sosa:hasResult ?result_phaeopigments .
  ?result_phaeopigments qudt:numericValue ?value_phaeopigments .
  FILTER(?value_phaeopigments <= 57.679654610587285)
  ?observations sosa:observedProperty ?pigments .
  ?pigments rdfs:label ?label_pigments .
  ?label_pigments onto:fts "pigments~5" .
  ?observations sosa:hasResult ?result_pigments .
  ?result_pigments qudt:numericValue ?value_pigments .
  FILTER(?value_pigments < 55.91475071009996)
  ?observations sosa:observedProperty ?sea_surf_temp .
  ?sea_surf_temp rdfs:label ?label_sea_surf_temp .
  ?label_sea_surf_temp onto:fts "sea_surf_temp~5" .
  ?observations sosa:hasResult ?result_sea_surf_temp .
  ?result_sea_surf_temp qudt:numericValue ?value_sea_surf_temp .
  FILTER(?value_sea_surf_temp > 42.43986967356904)
}