
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
  ?sample
  ?observatory
  ?event
  
  ?observations
  
  ?label_sea_subsurf_salinity
  ?result_sea_subsurf_salinity
  ?value_sea_subsurf_salinity
  ?label_down_par
  ?result_down_par
  ?value_down_par
  ?label_density
  ?result_density
  ?value_density
  ?taxonannotation
  ?taxonid
    
  ?rank
WHERE {
  ?sample a sosa:Sample .
  # link event
  ?sample sosa:isResultOf ?event .
  # link observatory
  ?event sampl:linkedToObservatory ?observatory .
  # Optional filters
  # name of observatory
  # depth filter
  
  ?observatory emobon:waterColumnDepth/qudt:numericValue ?depth_value .
  FILTER(?depth_value > 956.4714567828846) .
  # Marine Region (ID)
  ?observatory emobon:marineRegion ?mrgid . 
  FILTER regex(str(?mrgid), "http://marineregions.org/mrgid/1912") .
  # marineregion name
  ?observatory emobon:marineRegionName ?mrgn . 
  ?mrgn onto:fts ("Norwegian part of the Norwegian Sea~5") .
  ?event prov:startedAtTime ?datetime_begin . 
  
  # dateTime event
  FILTER(?datetime_begin >= "2023-06-12T21:32:20Z"^^xsd:date) .
  FILTER(?datetime_begin <= "2025-08-23T06:18:28Z"^^xsd:date) .
  # linking between taxon annotations and sample
  ?taxonannotation a prod:TaxonomicAnnotation .
  ?taxonannotation prod:ofSample ?sample .
  ?taxonannotation dct:identifier ?taxonid .
      
  ?taxonid dct:taxonRank ?rank .
  ?rank onto:fts ("family~5") .
  ?observations a sosa:Observation .
  ?observations sosa:hasFeatureOfInterest ?sample .
    
  ?observations sosa:observedProperty ?sea_subsurf_salinity .
  ?sea_subsurf_salinity rdfs:label ?label_sea_subsurf_salinity .
  ?label_sea_subsurf_salinity onto:fts "sea_subsurf_salinity~5" .
  ?observations sosa:hasResult ?result_sea_subsurf_salinity .
  ?result_sea_subsurf_salinity qudt:numericValue ?value_sea_subsurf_salinity .
  FILTER(?value_sea_subsurf_salinity <= 58.155799080252145)
  ?observations sosa:observedProperty ?down_par .
  ?down_par rdfs:label ?label_down_par .
  ?label_down_par onto:fts "down_par~5" .
  ?observations sosa:hasResult ?result_down_par .
  ?result_down_par qudt:numericValue ?value_down_par .
  FILTER(?value_down_par >= 28.07838398336727)
  ?observations sosa:observedProperty ?density .
  ?density rdfs:label ?label_density .
  ?label_density onto:fts "density~5" .
  ?observations sosa:hasResult ?result_density .
  ?result_density qudt:numericValue ?value_density .
  FILTER(?value_density < 85.97395857318908)
}