
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
  ?sample
  ?observatory
  ?event
  
  ?observations
  
  ?label_diss_oxygen
  ?result_diss_oxygen
  ?value_diss_oxygen
  ?label_ammonium
  ?result_ammonium
  ?value_ammonium
  ?taxonannotation
  ?taxonid
    
  ?rank
  ?lsuval
  ?ssuval
WHERE {
  ?sample a sosa:Sample .
  # link event
  ?sample sosa:isResultOf ?event .
  # link observatory
  ?event sampl:linkedToObservatory ?observatory .
  # Optional filters
  # name of observatory
  
  ?observatory emobon:observatoryId ?observatory_id .
  ?observatory_id onto:fts ("LMO~5 HCMR-1~5 ROSKOGO~5") .# depth filter
  
  # marineregion name
  ?observatory emobon:marineRegionName ?mrgn . 
  ?mrgn onto:fts ("Crete Sea~5") .
  ?event prov:startedAtTime ?datetime_begin . 
  
  # linking between taxon annotations and sample
  ?taxonannotation a prod:TaxonomicAnnotation .
  ?taxonannotation prod:ofSample ?sample .
  ?taxonannotation dct:identifier ?taxonid .
      
  ?taxonid dct:taxonRank ?rank .
  ?rank onto:fts ("phylum~5") .
  OPTIONAL {
    ?taxonannotation prod:lsuRNA ?lsuval .
    FILTER(?lsuval >= 89.57721636807446) . 
  }
  OPTIONAL {
    ?taxonannotation prod:ssuRNA ?ssuval .
    FILTER(?ssuval >= 89.57721636807446) .  
  }
  FILTER(BOUND(?lsuval) || BOUND(?ssuval))
  ?observations a sosa:Observation .
  ?observations sosa:hasFeatureOfInterest ?sample .
    
  ?observations sosa:observedProperty ?diss_oxygen .
  ?diss_oxygen rdfs:label ?label_diss_oxygen .
  ?label_diss_oxygen onto:fts "diss_oxygen~5" .
  ?observations sosa:hasResult ?result_diss_oxygen .
  ?result_diss_oxygen qudt:numericValue ?value_diss_oxygen .
  FILTER(?value_diss_oxygen > 67.3231179311598)
  ?observations sosa:observedProperty ?ammonium .
  ?ammonium rdfs:label ?label_ammonium .
  ?label_ammonium onto:fts "ammonium~5" .
  ?observations sosa:hasResult ?result_ammonium .
  ?result_ammonium qudt:numericValue ?value_ammonium .
  FILTER(?value_ammonium > 95.09715674344378)
}