
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
  ?sample
  ?observatory
  ?event
  
  ?observations
  
  ?label_sea_surf_salinity
  ?result_sea_surf_salinity
  ?value_sea_surf_salinity
  ?label_diss_oxygen
  ?result_diss_oxygen
  ?value_diss_oxygen
  ?label_phosphate
  ?result_phosphate
  ?value_phosphate
  ?taxonannotation
  ?taxonid
    ?sname
  ?lsuval
  ?ssuval
WHERE {
  ?sample a sosa:Sample .
  # link event
  ?sample sosa:isResultOf ?event .
  # link observatory
  ?event sampl:linkedToObservatory ?observatory .
  # Optional filters
  # name of observatory
  # depth filter
  
  ?observatory emobon:waterColumnDepth/qudt:numericValue ?depth_value .
  FILTER(?depth_value <= 959.4164306229511) .
  # marineregion name
  ?observatory emobon:marineRegionName ?mrgn . 
  ?mrgn onto:fts ("Western Channel~5") .
  ?event prov:startedAtTime ?datetime_begin . 
  
  # dateTime event
  FILTER(?datetime_begin >= "2023-07-08T03:26:41Z"^^xsd:date) .
  FILTER(?datetime_begin <= "2023-10-30T03:55:41Z"^^xsd:date) .
  # linking between taxon annotations and sample
  ?taxonannotation a prod:TaxonomicAnnotation .
  ?taxonannotation prod:ofSample ?sample .
  ?taxonannotation dct:identifier ?taxonid .
      
  ?taxonid dct:scientificName ?sname .
  ?sname onto:fts ("Pseudochattonella_farcimen~5") .
  OPTIONAL {
    ?taxonannotation prod:lsuRNA ?lsuval .
    FILTER(?lsuval >= 41.38888830853779) . 
  }
  OPTIONAL {
    ?taxonannotation prod:ssuRNA ?ssuval .
    FILTER(?ssuval >= 41.38888830853779) .  
  }
  FILTER(BOUND(?lsuval) || BOUND(?ssuval))
  ?observations a sosa:Observation .
  ?observations sosa:hasFeatureOfInterest ?sample .
    
  ?observations sosa:observedProperty ?sea_surf_salinity .
  ?sea_surf_salinity rdfs:label ?label_sea_surf_salinity .
  ?label_sea_surf_salinity onto:fts "sea_surf_salinity~5" .
  ?observations sosa:hasResult ?result_sea_surf_salinity .
  ?result_sea_surf_salinity qudt:numericValue ?value_sea_surf_salinity .
  FILTER(?value_sea_surf_salinity < 63.27867148016754)
  ?observations sosa:observedProperty ?diss_oxygen .
  ?diss_oxygen rdfs:label ?label_diss_oxygen .
  ?label_diss_oxygen onto:fts "diss_oxygen~5" .
  ?observations sosa:hasResult ?result_diss_oxygen .
  ?result_diss_oxygen qudt:numericValue ?value_diss_oxygen .
  FILTER(?value_diss_oxygen <= 70.13791897932572)
  ?observations sosa:observedProperty ?phosphate .
  ?phosphate rdfs:label ?label_phosphate .
  ?label_phosphate onto:fts "phosphate~5" .
  ?observations sosa:hasResult ?result_phosphate .
  ?result_phosphate qudt:numericValue ?value_phosphate .
  FILTER(?value_phosphate < 69.83274517688062)
}