
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
  ?sample
  ?observatory
  ?event
  
  ?observations
  
  ?label_organism_count
  ?result_organism_count
  ?value_organism_count
  ?label_sea_subsurf_temp
  ?result_sea_subsurf_temp
  ?value_sea_subsurf_temp
  ?label_conduc
  ?result_conduc
  ?value_conduc
  ?taxonannotation
  ?taxonid
    
  ?rank
WHERE {
  ?sample a sosa:Sample .
  # link event
  ?sample sosa:isResultOf ?event .
  # link observatory
  ?event sampl:linkedToObservatory ?observatory .
  # Optional filters
  # name of observatory
  # depth filter
  
  ?observatory emobon:waterColumnDepth/qudt:numericValue ?depth_value .
  FILTER(?depth_value <= 769.313667381254) .
  # Marine Region (ID)
  ?observatory emobon:marineRegion ?mrgid . 
  FILTER regex(str(?mrgid), "http://marineregions.org/mrgid/2350") .
  ?event prov:startedAtTime ?datetime_begin . 
  
  # linking between taxon annotations and sample
  ?taxonannotation a prod:TaxonomicAnnotation .
  ?taxonannotation prod:ofSample ?sample .
  ?taxonannotation dct:identifier ?taxonid .
      
  ?taxonid dct:taxonRank ?rank .
  ?rank onto:fts ("genus~5") .
  ?observations a sosa:Observation .
  ?observations sosa:hasFeatureOfInterest ?sample .
    
  ?observations sosa:observedProperty ?organism_count .
  ?organism_count rdfs:label ?label_organism_count .
  ?label_organism_count onto:fts "organism_count~5" .
  ?observations sosa:hasResult ?result_organism_count .
  ?result_organism_count qudt:numericValue ?value_organism_count .
  FILTER(?value_organism_count >= 89.69856654404421)
  ?observations sosa:observedProperty ?sea_subsurf_temp .
  ?sea_subsurf_temp rdfs:label ?label_sea_subsurf_temp .
  ?label_sea_subsurf_temp onto:fts "sea_subsurf_temp~5" .
  ?observations sosa:hasResult ?result_sea_subsurf_temp .
  ?result_sea_subsurf_temp qudt:numericValue ?value_sea_subsurf_temp .
  FILTER(?value_sea_subsurf_temp < 28.701932643071014)
  ?observations sosa:observedProperty ?conduc .
  ?conduc rdfs:label ?label_conduc .
  ?label_conduc onto:fts "conduc~5" .
  ?observations sosa:hasResult ?result_conduc .
  ?result_conduc qudt:numericValue ?value_conduc .
  FILTER(?value_conduc >= 65.64066553805606)
}