
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
  ?sample
  ?observatory
  ?event
  
  ?observations
  
  ?label_pigments
  ?result_pigments
  ?value_pigments
  ?label_ammonium
  ?result_ammonium
  ?value_ammonium
  ?label_nitrite
  ?result_nitrite
  ?value_nitrite
WHERE {
  ?sample a sosa:Sample .
  # link event
  ?sample sosa:isResultOf ?event .
  # link observatory
  ?event sampl:linkedToObservatory ?observatory .
  # Optional filters
  # name of observatory
  # depth filter
  
  # Marine Region (ID)
  ?observatory emobon:marineRegion ?mrgid . 
  FILTER regex(str(?mrgid), "http://marineregions.org/mrgid/25678") .
  ?event prov:startedAtTime ?datetime_begin . 
  
  ?observations a sosa:Observation .
  ?observations sosa:hasFeatureOfInterest ?sample .
    
  ?observations sosa:observedProperty ?pigments .
  ?pigments rdfs:label ?label_pigments .
  ?label_pigments onto:fts "pigments~5" .
  ?observations sosa:hasResult ?result_pigments .
  ?result_pigments qudt:numericValue ?value_pigments .
  FILTER(?value_pigments > 41)
  ?observations sosa:observedProperty ?ammonium .
  ?ammonium rdfs:label ?label_ammonium .
  ?label_ammonium onto:fts "ammonium~5" .
  ?observations sosa:hasResult ?result_ammonium .
  ?result_ammonium qudt:numericValue ?value_ammonium .
  FILTER(?value_ammonium > 67)
  ?observations sosa:observedProperty ?nitrite .
  ?nitrite rdfs:label ?label_nitrite .
  ?label_nitrite onto:fts "nitrite~5" .
  ?observations sosa:hasResult ?result_nitrite .
  ?result_nitrite qudt:numericValue ?value_nitrite .
  FILTER(?value_nitrite <= 95)
}