
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
  ?sample
  ?observatory
  ?event
  
  ?observations
  
  ?label_sea_subsurf_temp
  ?result_sea_subsurf_temp
  ?value_sea_subsurf_temp
  ?label_phaeopigments
  ?result_phaeopigments
  ?value_phaeopigments
  ?label_pigments
  ?result_pigments
  ?value_pigments
WHERE {
  ?sample a sosa:Sample .
  # link event
  ?sample sosa:isResultOf ?event .
  # link observatory
  ?event sampl:linkedToObservatory ?observatory .
  # Optional filters
  # name of observatory
  
  ?observatory emobon:observatoryId ?observatory_id .
  ?observatory_id onto:fts ("NRMCB~5") .# depth filter
  
  ?observatory emobon:waterColumnDepth/qudt:numericValue ?depth_value .
  FILTER(?depth_value > 344) .
  ?event prov:startedAtTime ?datetime_begin . 
  
  # dateTime event
  FILTER(?datetime_begin >= "2023-07-20T16:28:07Z"^^xsd:date) .
  FILTER(?datetime_begin <= "2024-05-26T16:21:33Z"^^xsd:date) .
  ?observations a sosa:Observation .
  ?observations sosa:hasFeatureOfInterest ?sample .
    
  ?observations sosa:observedProperty ?sea_subsurf_temp .
  ?sea_subsurf_temp rdfs:label ?label_sea_subsurf_temp .
  ?label_sea_subsurf_temp onto:fts "sea_subsurf_temp~5" .
  ?observations sosa:hasResult ?result_sea_subsurf_temp .
  ?result_sea_subsurf_temp qudt:numericValue ?value_sea_subsurf_temp .
  FILTER(?value_sea_subsurf_temp >= 0)
  ?observations sosa:observedProperty ?phaeopigments .
  ?phaeopigments rdfs:label ?label_phaeopigments .
  ?label_phaeopigments onto:fts "phaeopigments~5" .
  ?observations sosa:hasResult ?result_phaeopigments .
  ?result_phaeopigments qudt:numericValue ?value_phaeopigments .
  FILTER(?value_phaeopigments < 31)
  ?observations sosa:observedProperty ?pigments .
  ?pigments rdfs:label ?label_pigments .
  ?label_pigments onto:fts "pigments~5" .
  ?observations sosa:hasResult ?result_pigments .
  ?result_pigments qudt:numericValue ?value_pigments .
  FILTER(?value_pigments < 63)
}