
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
  ?sample
  ?observatory
  ?event
  
  ?observations
  
  ?label_sea_surf_salinity
  ?result_sea_surf_salinity
  ?value_sea_surf_salinity
  ?label_phosphate
  ?result_phosphate
  ?value_phosphate
  ?label_nitrate
  ?result_nitrate
  ?value_nitrate
  ?taxonannotation
  ?taxonid
    ?sname
  ?rank
WHERE {
  ?sample a sosa:Sample .
  # link event
  ?sample sosa:isResultOf ?event .
  # link observatory
  ?event sampl:linkedToObservatory ?observatory .
  # Optional filters
  # name of observatory
  # depth filter
  
  # marineregion name
  ?observatory emobon:marineRegionName ?mrgn . 
  ?mrgn onto:fts ("Mediterranean Sea - Western Basin~5") .
  ?event prov:startedAtTime ?datetime_begin . 
  
  # dateTime event
  FILTER(?datetime_begin >= "2024-05-09T07:37:19Z"^^xsd:date) .
  FILTER(?datetime_begin <= "2025-11-19T00:17:59Z"^^xsd:date) .
  # linking between taxon annotations and sample
  ?taxonannotation a prod:TaxonomicAnnotation .
  ?taxonannotation prod:ofSample ?sample .
  ?taxonannotation dct:identifier ?taxonid .
      
  ?taxonid dct:scientificName ?sname .
  ?sname onto:fts ("Actiniaria~5") .
  ?taxonid dct:taxonRank ?rank .
  ?rank onto:fts ("kingdom~5") .
  ?observations a sosa:Observation .
  ?observations sosa:hasFeatureOfInterest ?sample .
    
  ?observations sosa:observedProperty ?sea_surf_salinity .
  ?sea_surf_salinity rdfs:label ?label_sea_surf_salinity .
  ?label_sea_surf_salinity onto:fts "sea_surf_salinity~5" .
  ?observations sosa:hasResult ?result_sea_surf_salinity .
  ?result_sea_surf_salinity qudt:numericValue ?value_sea_surf_salinity .
  FILTER(?value_sea_surf_salinity < 83.22566668672643)
  ?observations sosa:observedProperty ?phosphate .
  ?phosphate rdfs:label ?label_phosphate .
  ?label_phosphate onto:fts "phosphate~5" .
  ?observations sosa:hasResult ?result_phosphate .
  ?result_phosphate qudt:numericValue ?value_phosphate .
  FILTER(?value_phosphate > 32.56748686143612)
  ?observations sosa:observedProperty ?nitrate .
  ?nitrate rdfs:label ?label_nitrate .
  ?label_nitrate onto:fts "nitrate~5" .
  ?observations sosa:hasResult ?result_nitrate .
  ?result_nitrate qudt:numericValue ?value_nitrate .
  FILTER(?value_nitrate > 69.98957166402018)
}