
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
  ?sample
  ?observatory
  ?event
  
  ?observations
  
  ?label_density
  ?result_density
  ?value_density
  ?label_redox_potential
  ?result_redox_potential
  ?value_redox_potential
  ?taxonannotation
  ?taxonid
    ?sname
  ?rank
WHERE {
  ?sample a sosa:Sample .
  # link event
  ?sample sosa:isResultOf ?event .
  # link observatory
  ?event sampl:linkedToObservatory ?observatory .
  # Optional filters
  # name of observatory
  
  ?observatory emobon:observatoryId ?observatory_id .
  ?observatory_id onto:fts ("NRMCB~5 LMO~5 AAOT~5") .# depth filter
  
  ?event prov:startedAtTime ?datetime_begin . 
  
  # dateTime event
  FILTER(?datetime_begin >= "2023-10-20T11:51:19Z"^^xsd:date) .
  FILTER(?datetime_begin <= "2025-03-18T03:41:45Z"^^xsd:date) .
  # linking between taxon annotations and sample
  ?taxonannotation a prod:TaxonomicAnnotation .
  ?taxonannotation prod:ofSample ?sample .
  ?taxonannotation dct:identifier ?taxonid .
      
  ?taxonid dct:scientificName ?sname .
  ?sname onto:fts ("Olpidiomycetes~5") .
  ?taxonid dct:taxonRank ?rank .
  ?rank onto:fts ("super kingdom~5") .
  ?observations a sosa:Observation .
  ?observations sosa:hasFeatureOfInterest ?sample .
    
  ?observations sosa:observedProperty ?density .
  ?density rdfs:label ?label_density .
  ?label_density onto:fts "density~5" .
  ?observations sosa:hasResult ?result_density .
  ?result_density qudt:numericValue ?value_density .
  FILTER(?value_density >= 35.93265178056957)
  ?observations sosa:observedProperty ?redox_potential .
  ?redox_potential rdfs:label ?label_redox_potential .
  ?label_redox_potential onto:fts "redox_potential~5" .
  ?observations sosa:hasResult ?result_redox_potential .
  ?result_redox_potential qudt:numericValue ?value_redox_potential .
  FILTER(?value_redox_potential > 2.213672406587386)
}