
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
  ?sample
  ?observatory
  ?event
  
  ?observations
  
  ?label_phaeopigments
  ?result_phaeopigments
  ?value_phaeopigments
  ?label_sediment_temp
  ?result_sediment_temp
  ?value_sediment_temp
  ?label_down_par
  ?result_down_par
  ?value_down_par
  ?taxonannotation
  ?taxonid
    ?sname
  ?rank
WHERE {
  ?sample a sosa:Sample .
  # link event
  ?sample sosa:isResultOf ?event .
  # link observatory
  ?event sampl:linkedToObservatory ?observatory .
  # Optional filters
  # name of observatory
  # depth filter
  
  ?event prov:startedAtTime ?datetime_begin . 
  
  # linking between taxon annotations and sample
  ?taxonannotation a prod:TaxonomicAnnotation .
  ?taxonannotation prod:ofSample ?sample .
  ?taxonannotation dct:identifier ?taxonid .
      
  ?taxonid dct:scientificName ?sname .
  ?sname onto:fts ("Siluaniidae~5") .
  ?taxonid dct:taxonRank ?rank .
  ?rank onto:fts ("order~5") .
  ?observations a sosa:Observation .
  ?observations sosa:hasFeatureOfInterest ?sample .
    
  ?observations sosa:observedProperty ?phaeopigments .
  ?phaeopigments rdfs:label ?label_phaeopigments .
  ?label_phaeopigments onto:fts "phaeopigments~5" .
  ?observations sosa:hasResult ?result_phaeopigments .
  ?result_phaeopigments qudt:numericValue ?value_phaeopigments .
  FILTER(?value_phaeopigments > 43.78265171302559)
  ?observations sosa:observedProperty ?sediment_temp .
  ?sediment_temp rdfs:label ?label_sediment_temp .
  ?label_sediment_temp onto:fts "sediment_temp~5" .
  ?observations sosa:hasResult ?result_sediment_temp .
  ?result_sediment_temp qudt:numericValue ?value_sediment_temp .
  FILTER(?value_sediment_temp >= 46.82616742095417)
  ?observations sosa:observedProperty ?down_par .
  ?down_par rdfs:label ?label_down_par .
  ?label_down_par onto:fts "down_par~5" .
  ?observations sosa:hasResult ?result_down_par .
  ?result_down_par qudt:numericValue ?value_down_par .
  FILTER(?value_down_par <= 15.119639393561945)
}