
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
  ?sample
  ?observatory
  ?event
  
  ?observations
  
  ?label_pressure
  ?result_pressure
  ?value_pressure
  ?label_sea_surf_temp
  ?result_sea_surf_temp
  ?value_sea_surf_temp
  ?label_organism_count
  ?result_organism_count
  ?value_organism_count
WHERE {
  ?sample a sosa:Sample .
  # link event
  ?sample sosa:isResultOf ?event .
  # link observatory
  ?event sampl:linkedToObservatory ?observatory .
  # Optional filters
  # name of observatory
  # depth filter
  
  ?event prov:startedAtTime ?datetime_begin . 
  
  ?observations a sosa:Observation .
  ?observations sosa:hasFeatureOfInterest ?sample .
    
  ?observations sosa:observedProperty ?pressure .
  ?pressure rdfs:label ?label_pressure .
  ?label_pressure onto:fts "pressure~5" .
  ?observations sosa:hasResult ?result_pressure .
  ?result_pressure qudt:numericValue ?value_pressure .
  FILTER(?value_pressure < 80.1387031205944)
  ?observations sosa:observedProperty ?sea_surf_temp .
  ?sea_surf_temp rdfs:label ?label_sea_surf_temp .
  ?label_sea_surf_temp onto:fts "sea_surf_temp~5" .
  ?observations sosa:hasResult ?result_sea_surf_temp .
  ?result_sea_surf_temp qudt:numericValue ?value_sea_surf_temp .
  FILTER(?value_sea_surf_temp <= 56.150538342354054)
  ?observations sosa:observedProperty ?organism_count .
  ?organism_count rdfs:label ?label_organism_count .
  ?label_organism_count onto:fts "organism_count~5" .
  ?observations sosa:hasResult ?result_organism_count .
  ?result_organism_count qudt:numericValue ?value_organism_count .
  FILTER(?value_organism_count >= 4.97806607183885)
}