
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
  ?sample
  ?observatory
  ?event
  
  ?observations
  
  ?label_silicate
  ?result_silicate
  ?value_silicate
  ?label_ammonium
  ?result_ammonium
  ?value_ammonium
  ?label_sea_surf_temp
  ?result_sea_surf_temp
  ?value_sea_surf_temp
  ?taxonannotation
  ?taxonid
    ?sname
WHERE {
  ?sample a sosa:Sample .
  # link event
  ?sample sosa:isResultOf ?event .
  # link observatory
  ?event sampl:linkedToObservatory ?observatory .
  # Optional filters
  # name of observatory
  
  ?observatory emobon:observatoryId ?observatory_id .
  ?observatory_id onto:fts ("MBAL4~5 PiEGetxo~5 NRMCB~5") .# depth filter
  
  ?event prov:startedAtTime ?datetime_begin . 
  
  # linking between taxon annotations and sample
  ?taxonannotation a prod:TaxonomicAnnotation .
  ?taxonannotation prod:ofSample ?sample .
  ?taxonannotation dct:identifier ?taxonid .
      
  ?taxonid dct:scientificName ?sname .
  ?sname onto:fts ("Isosphaerales~5") .
  ?observations a sosa:Observation .
  ?observations sosa:hasFeatureOfInterest ?sample .
    
  ?observations sosa:observedProperty ?silicate .
  ?silicate rdfs:label ?label_silicate .
  ?label_silicate onto:fts "silicate~5" .
  ?observations sosa:hasResult ?result_silicate .
  ?result_silicate qudt:numericValue ?value_silicate .
  FILTER(?value_silicate > 42)
  ?observations sosa:observedProperty ?ammonium .
  ?ammonium rdfs:label ?label_ammonium .
  ?label_ammonium onto:fts "ammonium~5" .
  ?observations sosa:hasResult ?result_ammonium .
  ?result_ammonium qudt:numericValue ?value_ammonium .
  FILTER(?value_ammonium > 18)
  ?observations sosa:observedProperty ?sea_surf_temp .
  ?sea_surf_temp rdfs:label ?label_sea_surf_temp .
  ?label_sea_surf_temp onto:fts "sea_surf_temp~5" .
  ?observations sosa:hasResult ?result_sea_surf_temp .
  ?result_sea_surf_temp qudt:numericValue ?value_sea_surf_temp .
  FILTER(?value_sea_surf_temp < 20)
}