
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
  ?sample
  ?observatory
  ?event
  
  ?observations
  
  ?label_sea_subsurf_salinity
  ?result_sea_subsurf_salinity
  ?value_sea_subsurf_salinity
  ?label_sea_subsurf_temp
  ?result_sea_subsurf_temp
  ?value_sea_subsurf_temp
  ?label_conduc
  ?result_conduc
  ?value_conduc
  ?taxonannotation
  ?taxonid
    ?sname
  ?rank
WHERE {
  ?sample a sosa:Sample .
  # link event
  ?sample sosa:isResultOf ?event .
  # link observatory
  ?event sampl:linkedToObservatory ?observatory .
  # Optional filters
  # name of observatory
  
  ?observatory emobon:observatoryId ?observatory_id .
  ?observatory_id onto:fts ("MBAL4~5 RFormosa~5 OSD74~5") .# depth filter
  
  ?observatory emobon:waterColumnDepth/qudt:numericValue ?depth_value .
  FILTER(?depth_value < 658) .
  # marineregion name
  ?observatory emobon:marineRegionName ?mrgn . 
  ?mrgn onto:fts ("Belgian part of the North Sea~5") .
  ?event prov:startedAtTime ?datetime_begin . 
  
  # dateTime event
  FILTER(?datetime_begin >= "2023-06-13T16:57:13Z"^^xsd:date) .
  FILTER(?datetime_begin <= "2025-08-11T16:07:07Z"^^xsd:date) .
  # linking between taxon annotations and sample
  ?taxonannotation a prod:TaxonomicAnnotation .
  ?taxonannotation prod:ofSample ?sample .
  ?taxonannotation dct:identifier ?taxonid .
      
  ?taxonid dct:scientificName ?sname .
  ?sname onto:fts ("Glaciecola_sp._Za3-19~5") .
  ?taxonid dct:taxonRank ?rank .
  ?rank onto:fts ("genus~5") .
  ?observations a sosa:Observation .
  ?observations sosa:hasFeatureOfInterest ?sample .
    
  ?observations sosa:observedProperty ?sea_subsurf_salinity .
  ?sea_subsurf_salinity rdfs:label ?label_sea_subsurf_salinity .
  ?label_sea_subsurf_salinity onto:fts "sea_subsurf_salinity~5" .
  ?observations sosa:hasResult ?result_sea_subsurf_salinity .
  ?result_sea_subsurf_salinity qudt:numericValue ?value_sea_subsurf_salinity .
  FILTER(?value_sea_subsurf_salinity <= 33)
  ?observations sosa:observedProperty ?sea_subsurf_temp .
  ?sea_subsurf_temp rdfs:label ?label_sea_subsurf_temp .
  ?label_sea_subsurf_temp onto:fts "sea_subsurf_temp~5" .
  ?observations sosa:hasResult ?result_sea_subsurf_temp .
  ?result_sea_subsurf_temp qudt:numericValue ?value_sea_subsurf_temp .
  FILTER(?value_sea_subsurf_temp > 82)
  ?observations sosa:observedProperty ?conduc .
  ?conduc rdfs:label ?label_conduc .
  ?label_conduc onto:fts "conduc~5" .
  ?observations sosa:hasResult ?result_conduc .
  ?result_conduc qudt:numericValue ?value_conduc .
  FILTER(?value_conduc > 5)
}