
PREFIX prod: <https://data.emobon.embrc.eu/ns/product#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX emobon: <https://data.emobon.embrc.eu/ns/core#>
PREFIX sampl: <https://data.emobon.embrc.eu/ns/sampling#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX onto: <http://www.ontotext.com/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT
  ?sample
  ?observatory
  ?event
  
  ?observations
  
  ?label_phosphate
  ?result_phosphate
  ?value_phosphate
  ?label_sea_subsurf_temp
  ?result_sea_subsurf_temp
  ?value_sea_subsurf_temp
  ?taxonannotation
  ?taxonid
    ?sname
  ?rank
WHERE {
  ?sample a sosa:Sample .
  # link event
  ?sample sosa:isResultOf ?event .
  # link observatory
  ?event sampl:linkedToObservatory ?observatory .
  # Optional filters
  # name of observatory
  # depth filter
  
  # Marine Region (ID)
  ?observatory emobon:marineRegion ?mrgid . 
  FILTER regex(str(?mrgid), "http://marineregions.org/mrgid/3610") .
  # marineregion name
  ?observatory emobon:marineRegionName ?mrgn . 
  ?mrgn onto:fts ("North Sea~5") .
  ?event prov:startedAtTime ?datetime_begin . 
  
  # dateTime event
  FILTER(?datetime_begin >= "2025-05-24T13:56:10Z"^^xsd:date) .
  FILTER(?datetime_begin <= "2025-07-13T14:16:37Z"^^xsd:date) .
  # linking between taxon annotations and sample
  ?taxonannotation a prod:TaxonomicAnnotation .
  ?taxonannotation prod:ofSample ?sample .
  ?taxonannotation dct:identifier ?taxonid .
      
  ?taxonid dct:scientificName ?sname .
  ?sname onto:fts ("Picomonas~5") .
  ?taxonid dct:taxonRank ?rank .
  ?rank onto:fts ("species~5") .
  ?observations a sosa:Observation .
  ?observations sosa:hasFeatureOfInterest ?sample .
    
  ?observations sosa:observedProperty ?phosphate .
  ?phosphate rdfs:label ?label_phosphate .
  ?label_phosphate onto:fts "phosphate~5" .
  ?observations sosa:hasResult ?result_phosphate .
  ?result_phosphate qudt:numericValue ?value_phosphate .
  FILTER(?value_phosphate >= 62)
  ?observations sosa:observedProperty ?sea_subsurf_temp .
  ?sea_subsurf_temp rdfs:label ?label_sea_subsurf_temp .
  ?label_sea_subsurf_temp onto:fts "sea_subsurf_temp~5" .
  ?observations sosa:hasResult ?result_sea_subsurf_temp .
  ?result_sea_subsurf_temp qudt:numericValue ?value_sea_subsurf_temp .
  FILTER(?value_sea_subsurf_temp > 4)
}