prefix prod: <https://data.emobon.embrc.eu/ns/product#> 
prefix dct: <http://purl.org/dc/terms/>
select ?sname ?rank (count(?annotation) as ?annotationCount) where { 
  ?annotation a prod:TaxonomicAnnotation .
  ?annotation dct:identifier ?id .
  ?id dct:scientificName ?sname .
  ?id dct:taxonRank ?rank .
} group by ?sname ?rank
order by desc(?annotationCount)
