PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX purl: <http://purl.org/dc/terms/>
SELECT DISTINCT ?identifier
WHERE  {
	?observations a sosa:Observation .
    ?observations sosa:observedProperty ?property .
    ?property purl:identifier ?identifier .
}